workspaces:
  workspace_data: "4d0f636a-9dfc-4ade-b6ef-bbd3ffa6d656"
  workspace_code: "4d0f636a-9dfc-4ade-b6ef-bbd3ffa6d656"
  workspace_business_domain_data: "4d0f636a-9dfc-4ade-b6ef-bbd3ffa6d656"
  workspace_business_domain_code: "4d0f636a-9dfc-4ade-b6ef-bbd3ffa6d656"
  workspace_config: "4d0f636a-9dfc-4ade-b6ef-bbd3ffa6d656"
  workspace_business_domain_reporting: "4d0f636a-9dfc-4ade-b6ef-bbd3ffa6d656"

connections:
  CON_FMD_FABRIC_SQL: "372237f9-709a-48f8-8fb2-ce06940c990e"
  CON_FMD_FABRIC_PIPELINES: "6d8146c6-a438-47df-94e2-540c552eb6d7"
  CON_FMD_ADF_PIPELINES: "02e107b8-e97e-4b00-a28c-668cf9ce3d9a"
  CON_FMD_FABRIC_NOTEBOOKS: "5929775e-aff1-430c-b56e-f855d0bc63b8"

database:
  displayName: "SQL_FMD_FRAMEWORK"
  id: "075e5656-613d-41f4-89ed-63f6837c0ff6"
  endpoint: "nl7yhqnbrscude3yv6mas6bxpq-tndhi54vbs4urpccunwiydulzi.datawarehouse.fabric.microsoft.com,1433"
